### ISSUE TITLE
Don't include source in wheel builds

### ISSUE THREAD

**Issue by scaramallion** [pydicom/pylibjpeg-openjpeg#43]
Try and figure out how to not include the C source files with the wheel builds ([see also](https://twitter.com/eborisch/status/1324014037206708226)).

**Comment by wvxvw** [comment]
Hey, I came here puzzled by your MANIFEST.in file which tells not only to include C source, but also CMake utilities and a bunch of other unnecessary stuff. Since I'm working on an Anaconda packaging, all those *.bin files run `conda-build` the wrong way. Would it be possible to exclude the entire `openjpeg/src/openjpeg` directory from the wheel?

**Comment by wvxvw** [comment]
Also, you have, in `setup.py`:

``` python
include_package_data = True,
```

Which is the reason why when you'd run `setup.py bdist_wheel` you'd get all those C source files and other stuff that's not Pythons source.

**Comment by scaramallion** [comment]
My original thinking was that the source files would be needed if the package [needed to be rebuilt](https://github.com/pydicom/pylibjpeg-openjpeg/issues/45) during install (for whatever reason). Since I'd prefer not to rely on the library already being installed.

But I'm pretty new to this, maybe there's a better way?

**Comment by wvxvw** [comment]
Well, MANIFEST.in is only considered for source distributions, but, my understanding is that `include_package_data` will just grab everything in the source directory and put it in the wheel, even if it's a binary wheel.

I'm not really sure what's the best practice is about including a dependent library in the source distribution... To be fair, I don't really understand who are the intended audience of source distribution. In practice, it ends up being people who either somehow screwed their Python setup in such a way that they cannot install binary packages, or people on unsupported platforms (eg. weird compiler / ARM architecture etc.) The second case sounds legitimate, but, on the other hand, if this is the case, why not just clone the Git repository and build from there?

There's another weird thing about source distributions. Someone may try installing them by running `setup.py install` rather than building a wheel / egg and installing that... and that screws with the layout of an install (i.e. puts files in unexpected location).

At work, I just tell people never to use `setup.py install` or equivalent `pip` command to prevent the above from happening. Or, if, I can, I override the `setup.py install` to do the equivalent of `setup.py bdist_egg && easy_install ./dist/*.egg`, I'd do that... but this is a lot of work... because it also means overriding every other possible `setuptools` command that needs installing (eg. `setup.py test`).

Anyways, for now I changed `include_package_data` to `package_data` with manually specifying only the source files that belong to `pylibjpeg-openjpeg` but not those coming from the submodule + this requires manually specifying packages to build (instead of calling `find_packages()`. I'll see what I can do about source distribution. If you think it's best to keep all  the CMake stuff in it, then I'll keep it there.

**Comment by wvxvw** [comment]
Oh, I wrote this before reading about the problem in another ticket. It's funny, I kinda guessed what the problem was.

Idk... in the case of that person, I'd just tell them to do a Git checkout and build from Git. They chose to work with a bad OS, unsupported CPU architecture--it's on them to deal with the consequences... if because of people like this everyone else needs to get files in the package they have never asked for, that doesn't sound like a good deal.
